### ISSUE TITLE
ArrayIndexOutOfBoundsException with invalid Plot Auto - Command

### ISSUE THREAD

**Issue by BlockyTheDev** [Blocky38/PlotSquared-Legacy#1]
**Befehl**
`/plot auto 4`

**File**
`https://github.com/IntellectualSites/PlotSquared-Legacy/blob/2ea050744c68700d6fc4066f08700e06bcd7c233/Core/src/main/java/com/intellectualcrafters/plot/commands/Auto.java`

**Type**
`java.lang.ArrayIndexOutOfBoundsException`

**ERROR**
```
[17:39:07 INFO]: Blocky38 issued server command: /p auto 4
[17:39:07 WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[17:39:07 WARN]:        at com.intellectualcrafters.plot.commands.Auto.onCommand(Auto.java:65)
[17:39:07 WARN]:        at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
[17:39:07 WARN]:        at com.plotsquared.general.commands.Command.execute(Command.java:323)
[17:39:07 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259)
[17:39:07 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[17:39:07 WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[17:39:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:39:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:39:07 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:39:07 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:39:07 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:39:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:39:07 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

- [ ] Fixed

**Comment by BlockyTheDev** [comment]
# Closed because of archive
